# Generated by Django 5.1.4 on 2025-07-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
