# Generated by Django 5.1.4 on 2025-07-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_booking_booking_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bottle_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
