# Generated by Django 5.1.4 on 2025-07-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_booking_bottle_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
